#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/JPOrnament.jar:$APPDIR/lib/resources.jar:$APPDIR/lib/rt.jar:$APPDIR/lib/jsse.jar:$APPDIR/lib/jce.jar:$APPDIR/lib/charsets.jar:$APPDIR/lib/dnsns.jar:$APPDIR/lib/localedata.jar:$APPDIR/lib/sunjce_provider.jar:$APPDIR/lib/core.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/minim-spi.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/controlP5.jar"JPOrnament
